### ISSUE TITLE
Implement Agreed on model changes for new Threat Dashboard + CRUD Services to manipulate

### ISSUE THREAD

**Issue by mpmmasterpeace** [unfetter-discover/unfetter#1413]
### Tasks

- [x] Use proposed model changes (https://wiki.codev.mitre.org/display/UNFETTER/Data+Model) to update Mongo store

- [x] Implement CRUD services to manipulate objects

**Comment by j987987** [comment]
- [ ] Update STIX package with new object
